steps:
  - label: ":postgres: Run Tests - Postgres"
    key: "run-dbt-postgres"
    plugins:
      - docker#v3.13.0:
          image: "python:3.8"
          shell: [ "/bin/bash", "-e", "-c" ]
          environment:
            - "BASH_ENV=/tmp/.bashrc"
            - "CI_POSTGRES_DBT_DBNAME"
            - "CI_POSTGRES_DBT_HOST"
            - "CI_POSTGRES_DBT_PASS"
            - "CI_POSTGRES_DBT_USER"
    commands: |
      bash .buildkite/scripts/run_models.sh postgres 

  - label: ":snowflake-db: Run Tests - Snowflake"
    key: "run_dbt_snowflake"
    plugins:
      - docker#v3.13.0:
          image: "python:3.8"
          shell: [ "/bin/bash", "-e", "-c" ]
          environment:
            - "BASH_ENV=/tmp/.bashrc"
            - "CI_SNOWFLAKE_DBT_ACCOUNT"
            - "CI_SNOWFLAKE_DBT_DATABASE"
            - "CI_SNOWFLAKE_DBT_PASS"
            - "CI_SNOWFLAKE_DBT_ROLE"
            - "CI_SNOWFLAKE_DBT_USER"
            - "CI_SNOWFLAKE_DBT_WAREHOUSE"
    commands: |
      bash .buildkite/scripts/run_models.sh snowflake

  - label: ":gcloud: Run Tests - BigQuery"
    key: "run_dbt_bigquery"
    plugins:
      - docker#v3.13.0:
          image: "python:3.8"
          shell: [ "/bin/bash", "-e", "-c" ]
          environment:
            - "BASH_ENV=/tmp/.bashrc"
            - "GCLOUD_SERVICE_KEY"
    commands: |
      bash .buildkite/scripts/run_models.sh bigquery

  - label: ":amazon-redshift: Run Tests - Redshift"
    key: "run_dbt_redshift"
    plugins:
      - docker#v3.13.0:
          image: "python:3.8"
          shell: [ "/bin/bash", "-e", "-c" ]
          environment:
            - "BASH_ENV=/tmp/.bashrc"
            - "CI_REDSHIFT_DBT_DBNAME"
            - "CI_REDSHIFT_DBT_HOST"
            - "CI_REDSHIFT_DBT_PASS"
            - "CI_REDSHIFT_DBT_USER"
    commands: |
      bash .buildkite/scripts/run_models.sh redshift

  - label: ":bricks: Run Tests - Databricks"
    key: "run_dbt_databricks"
    plugins:
      - docker#v3.13.0:
          image: "python:3.8"
          shell: [ "/bin/bash", "-e", "-c" ]
          environment:
            - "BASH_ENV=/tmp/.bashrc"
            - "CI_DATABRICKS_DBT_HOST"
            - "CI_DATABRICKS_DBT_HTTP_PATH"
            - "CI_DATABRICKS_DBT_TOKEN"
    commands: |
      bash .buildkite/scripts/run_models.sh databricks