name: Check docs current

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-docs:
    uses: fivetran/dbt_package_automations/.github/workflows/check-docs-current.yml@docs-generator-status-report
    secrets: inherit